In [1]:
import pandas as pd

In [15]:
df=pd.read_csv('Plant_1_Generation_Data.csv')

In [16]:
df

,DATE_TIME,PLANT_ID,SOURCE_KEY,DC_POWER,AC_POWER,DAILY_YIELD,TOTAL_YIELD
0,15-05-2020 00:00,4135001,1BY6WEcLGh8j5v7,0.0,0.0,0.000,6259559.0
1,15-05-2020 00:00,4135001,1IF53ai7Xc0U56Y,0.0,0.0,0.000,6183645.0
2,15-05-2020 00:00,4135001,3PZuoBAID5Wc2HD,0.0,0.0,0.000,6987759.0
3,15-05-2020 00:00,4135001,7JYdWkrLSPkdwr4,0.0,0.0,0.000,7602960.0
4,15-05-2020 00:00,4135001,McdE0feGgRqW7Ca,0.0,0.0,0.000,7158964.0
...,...,...,...,...,...,...,...
68773,17-06-2020 23:45,4135001,uHbuxQJl8lW7ozc,0.0,0.0,5967.000,7287002.0
68774,17-06-2020 23:45,4135001,wCURE6d3bPkepu2,0.0,0.0,5147.625,7028601.0
68775,17-06-2020 23:45,4135001,z9Y9gH1T5YWrNuG,0.0,0.0,5819.000,7251204.0
68776,17-06-2020 23:45,4135001,zBIq5rxdHJRwDNY,0.0,0.0,5817.000,6583369.0
68777,17-06-2020 23:45,4135001,zVJPv84UY57bAof,0.0,0.0,5910.000,7363272.0

In [17]:
df=df.groupby(['DATE_TIME']).sum()

In [22]:
df['TOTAL_YIELD'][100:200]

DATE_TIME
02-06-2020 01:00    153646938.0
02-06-2020 01:15    153646938.0
02-06-2020 01:30    153646938.0
02-06-2020 01:45    153646938.0
02-06-2020 02:00    153646938.0
                       ...
03-06-2020 00:45    153808916.0
03-06-2020 01:00    153808916.0
03-06-2020 01:15    153808916.0
03-06-2020 01:30    153808916.0
03-06-2020 01:45    153808916.0
Name: TOTAL_YIELD, Length: 100, dtype: float64